name: test_actions
description: A Flutter plugin that helps you in integration tests for your app.
version: 0.0.1
author: Leonardo Pizio
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.3
  flutter_test:
    sdk: flutter

flutter:
