name: test_actions
description: A Flutter plugin that helps you in integration tests for your app.
version: 0.2.1
homepage:
repository: https://github.com/leopi99/test_actions
publish_to: https://pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.3

flutter:
